--- 
- name: Advance cluster security - init bundle operation
  hosts: localhost
  gather_facts: false
  vars:
    ecslab_passwd: "ecslab"
  tasks:
  - name: Login to ocp
    shell: oc login https://api-int.lab.ocp.lan:6443 -u ecslab -p "{{ ecslab_passwd }}" --kubeconfig=ecslab-kubeconfig --insecure-skip-tls-verify
  - name: import acs operator roles
    import_role:
      name: operator_status
  - name: import  init-bundle roles
    import_role:
      name: init_bundle
 
