---
- name: get ACS admin token
  k8s_info: 
    api_version: v1
    kind: Secret
    namespace: rhacs-operator
    name: central-htpasswd
  environment:
      KUBECONFIG: ecslab-kubeconfig
  register: acs_secret
- name: acs admin password
  set_fact:
    admin_passwd: "{{ acs_secret.resources[0].data.password | b64decode }}"
- name: acs admin token
  uri:
    url:  https://central-rhacs-operator.apps.lab.ocp.lan/v1/apitokens/generate
    method: POST  
    body: 
      name: admin
      role: Admin  
    headers:
      Content-Type: "application/json"
    user: admin
    password: "{{ admin_passwd }}"
    force_basic_auth: true
    body_format: json
    validate_certs: no
  register: acs_token
- name: acs admin token
  debug:
    msg: "{{ acs_token.json.token }}"
- name: create init-bundle
  uri:
    url:  https://central-rhacs-operator.apps.lab.ocp.lan/v1/cluster-init/init-bundles
    method: POST  
    body: 
      name: "init_bundle_{{ ocp_cluster_name }}{% if init_bundle_name %}_{{ init_bundle_name }}{% endif %}"
    headers:
      Content-Type: "application/json"
      Authorization: "Bearer {{ acs_token.json.token }}"
      accept: "application/json"
    validate_certs: no
    body_format: json
  register: init_bundle
- name: get the init-bundle
  debug:
    msg: "{{ init_bundle.json.kubectlBundle}}"
- name: get the credintials type
  uri:
    url:  https://192.168.34.21/api/controller/v2/credential_types/?name=ecs_init_bundle
    method: GET
    user: admin
    password: db
    force_basic_auth: true
    headers:
      content-type: "application/json"
    validate_certs: no
    body_format: json
  register: cred_type
- name: get the credintials type
  debug:
    msg: "{{ cred_type.json.results[0].id }}"
- name: create init-bundle credentials
  uri:
    url:  https://192.168.34.21/api/controller/v2/credentials/
    method: POST
    body: 
      name: "ecs_init_bundle_{{ ocp_cluster_name }}{% if init_bundle_name %}_{{ init_bundle_name }}{% endif %}"
      credential_type: "{{ cred_type.json.results[0].id }}"
      organization: 1
      inputs: 
        init_bundle: "{{ init_bundle.json.kubectlBundle }}"
    user: admin
    password: db
    force_basic_auth: true
    headers:
      content-type: "application/json"  
    validate_certs: no
    body_format: json
    status_code: [200, 201]
  register: cred



 
